export const FIELD_DESCRIPTIONS: Record<string, { name: string; desc: string }> = {
  // EVENTS
  "field_email": { name: "Email (Obrigatório)", desc: "Email do lead em minúsculas e sem espaços." },
  "field_phone": { name: "Telefone", desc: "Número de WhatsApp ou celular de contato." },
  "field_name": { name: "Nome do Cliente", desc: "Nome do Lead (Opcional)." },
  "data": { name: "Data do Evento", desc: "Data na qual ele entrou na página/formulário." },
  "field_conversion_type": { name: "Tipo do Evento", desc: "Ex: 'Lead', 'PageView', 'Schedule'." },
  "field_conversion": { name: "Tag de Funil / Evento", desc: "Nome que o Lead recebe. Ex: 'Inscrição no Lançamento A'." },
  "idform": { name: "ID / Nome do Formulário", desc: "Identifica em qual ponto físico do site ele preencheu dados." },
  "url_page_host": { name: "URL Host", desc: "Domínio Principal." },
  "url_page_path": { name: "URL Path", desc: "Caminho da URL final." },
  "url_page_param": { name: "URL Parâmetros", desc: "Parâmetros pós-'?'" },
  "utm_source": { name: "UTM Source (Origem)", desc: "Canal. Ex: 'facebook_ads', 'google'." },
  "utm_medium": { name: "UTM Medium (Meio)", desc: "Público do anúncio." },
  "utm_campaign": { name: "UTM Campaign (Campanha)", desc: "Campanha Paga." },
  "utm_content": { name: "UTM Content (Conteúdo)", desc: "Nome do Criativo." },
  "utm_term": { name: "UTM Term (Termo)", desc: "Público Search ou termo do anúncio." },
  "field_action": { name: "Etapa do Funil Comercial", desc: "Usado para CRM Comercial longo." },
  "field_form_type": { name: "Canal de Contato", desc: "Ex: Formulário, Inbound Whatsapp, Telefone." },

  // TRANSACTIONS
  "field_transaction_code": { name: "ID Transação/Pedido (Obrigatório)", desc: "ID único daquela compra. Essencial para não duplicar vendas." },
  "field_transaction_date": { name: "Data da Transação (Obrigatório)", desc: "Data que o pedido foi feito na plataforma (Não usar update)." },
  "field_product": { name: "Nome do Produto (Obrigatório)", desc: "Nome comercial do seu curso/serviço." },
  "field_product_code": { name: "ID/SKU do Produto", desc: "Código identificador do plano interno." },
  "field_quantity": { name: "Quantidade Comprada", desc: "Quantidade do mesmo produto que foi para o carrinho." },
  "field_transaction_value": { name: "Valor Transacionado Bruto", desc: "Quanto valia a transação cheia (sem tirar taxa)." },
  "field_net_value": { name: "Valor Líquido", desc: "Lucro ou Valor real que caiu após a remoção de taxas." },
  "field_marketplace_comission": { name: "Comissão/Taxa da Plataforma", desc: "Quanto a plataforma cobrou pelo processamento." },
  "field_transaction_status": { name: "Status da Transação (Obrigatório)", desc: "Aprovado, Aguardando, Boleto Impresso, Chargeback." },
  "field_cancellation_date": { name: "Data de Cancelamento/Refund", desc: "Data que ocorreu o Churn ou solicitação do estorno." },
  "field_offer": { name: "Variante da Oferta", desc: "Variação de precificação ou oferta (Descontos nativos)." },
  "field_offer_code": { name: "Código da Oferta", desc: "Código interno da oferta." },
  "field_source": { name: "Plataforma/Gateway", desc: "Onde ela foi feita. Ex: Hotmart, Kiwify, MercadoPago." },
  "field_charge_type": { name: "Tipo de Cobrança", desc: "Ex: Cobrança Única Mensalidade Avulsa ou Recorrência Fixa." },
  "conversion": { name: "Tag / Evento", desc: "O que registou essa compra via UTM orgânica?" },
  "field_payment_method": { name: "Meio de Pagamento", desc: "Cartão de Crédito, PIX, Boleto." },
  "field_installments": { name: "Número de Parcelas", desc: "Quantas vezes a pessoa usou o cartão." },
  "field_charge_amount": { name: "Ordem Mensalidade (Recorrência)", desc: "Mensalidade 1? Renovação 3?" },
  "field_transaction_type": { name: "Tipo de Item Vendido", desc: "Item principal ou Order Bump / Upsell?" },
  "field_coupon": { name: "Cupom de Desconto", desc: "Cupom aplicado no checkout." },
  "field_zip_code": { name: "CEP / Zip Code", desc: "CEP para cálculo de frete ou região." },
  "field_state": { name: "Estado (UF)", desc: "" },
  "field_city": { name: "Cidade", desc: "" },
  "field_neighborhood": { name: "Bairro", desc: "" },

  // SURVEY
  "field_income": { name: "Renda Individual", desc: "Salário / lucro bruto declarado." },
  "field_familiar_income": { name: "Renda Familiar Agregada", desc: "Montante familiar." },
  "field_wage_range": { name: "Faixa Salarial IBGE", desc: "Ex: Classe A, B, C." },
  "field_age": { name: "Idade Ativa", desc: "Idade ou data de nascimento." },
  "field_gender": { name: "Gênero Declarado", desc: "Homem, Mulher, Outros..." },
  "field_education": { name: "Escolaridade e Graduação", desc: "Analfabeto, Nível Superior..." },
  "field_profession": { name: "Cargo Atual / Profissão", desc: "Engenheiro, Médico." },
  "field_profession_area": { name: "Ecossistema/Saga de Indústria", desc: "Tecnologia, Saúde, Educação." },
  "field_region": { name: "Região Demográfica", desc: "Norte, Sul, Sudeste." },
  "field_time_following": { name: "Há quanto tempo nos segue?", desc: "Mapeia maturidade antes do cliente entrar." },
  "field_nps": { name: "NPS (Satisfação 0-10)", desc: "Mede detrator x promotor." }
};

export const TRANS_STATUS_MAP: Record<string, string> = {
  'paid': 'approved', 'approved': 'approved', 'paga': 'approved', 'aprovada': 'approved',
  'completo': 'approved', 'concluída': 'approved', 'concluida': 'approved', 'entregue': 'approved',
  'aprovado': 'approved', 'success': 'approved', 'authorized': 'approved',
  'waiting_payment': 'pending', 'pending': 'pending', 'pendente': 'pending',
  'aguardando_pagamento': 'pending', 'em_processamento': 'pending', 'waiting': 'pending',
  'aguardando': 'pending', 'boleto_impresso': 'pending', 'billet_printed': 'pending',
  'refused': 'cancelled', 'cancelled': 'cancelled', 'cancelada': 'cancelled', 'failed': 'cancelled',
  'rejeitada': 'cancelled', 'cancelado': 'cancelled', 'negada': 'cancelled', 'falhou': 'cancelled',
  'estornado_por_fraude': 'cancelled',
  'refunded': 'refunded', 'reembolsada': 'refunded', 'estornada': 'refunded', 'reembolsado': 'refunded',
  'chargeback': 'refunded', 'contestada': 'refunded'
};

export const HARD_MAPPINGS: Record<string, string> = {
  "Código da transação": "field_transaction_code",
  "Nome do(a) Afiliado(a) + Comprador(a)": "field_name",
  "Email do(a) Comprador(a)": "field_email",
  "Telefone": "field_phone",
  "Documento": "field_cpf",
  "Data da transação": "field_transaction_date",
  "Código do produto + Produto + Faturamento líquido do(a) Produtor(a) + Faturamento do(a) Coprodutor(a) + Transação do Produto Principal": "field_product",
  "Status da transação": "field_transaction_status",
  "Faturamento líquido": "field_net_value",
};

export const UNIVERSAL_PRESETS: Record<string, string> = {
  "email": "field_email",
  "e-mail": "field_email",
  "name": "field_name",
  "nome": "field_name",
  "telefone": "field_phone",
  "phone": "field_phone",
  "utm_source": "utm_source",
  "source": "utm_source",
};
