export const FIELD_DESCRIPTIONS: Record<string, { name: string; desc: string; category: 'global' | 'events' | 'transactions' | 'survey' }> = {
    // GLOBAL / SHARED
    "field_email": {"name": "Email (Obrigatório)", "desc": "Email do lead em minúsculas e sem espaços.", "category": "global" },
    "field_phone": {"name": "Telefone", "desc": "Número de WhatsApp ou celular de contato.", "category": "global" },
    "field_name": {"name": "Nome do Cliente", "desc": "Nome do Lead (Opcional).", "category": "global" },
    "utm_source": {"name": "UTM Source (Origem)", "desc": "Canal. Ex: 'facebook_ads', 'google'.", "category": "global" },
    "utm_medium": {"name": "UTM Medium (Meio)", "desc": "Público do anúncio.", "category": "global" },
    "utm_campaign": {"name": "UTM Campaign (Campanha)", "desc": "Campanha Paga.", "category": "global" },
    "utm_content": {"name": "UTM Content (Conteúdo)", "desc": "Nome do Criativo.", "category": "global" },
    "utm_term": {"name": "UTM Term (Termo)", "desc": "Público Search ou termo do anúncio.", "category": "global" },
    "idform": {"name": "ID / Nome do Formulário", "desc": "Identifica em qual ponto físico do site ele preencheu dados.", "category": "global" },

    // EVENTS
    "data": {"name": "Data do Evento", "desc": "Data na qual ele entrou na página/formulário.", "category": "events" },
    "field_conversion_type": {"name": "Tipo do Evento", "desc": "Ex: 'Lead', 'PageView', 'Schedule'.", "category": "events" },
    "field_conversion": {"name": "Tag de Funil / Evento", "desc": "Nome que o Lead recebe. Ex: 'Inscrição no Lançamento A'.", "category": "events" },
    "url_page_host": {"name": "URL Host", "desc": "Domínio Principal.", "category": "events" },
    "url_page_path": {"name": "URL Path", "desc": "Caminho da URL final.", "category": "events" },
    "url_page_param": {"name": "URL Parâmetros", "desc": "Parâmetros pós-'?'", "category": "events" },
    "field_action": {"name": "Etapa do Funil Comercial", "desc": "Usado para CRM Comercial longo.", "category": "events" },
    "field_form_type": {"name": "Canal de Contato", "desc": "Ex: Formulário, Inbound Whatsapp, Telefone.", "category": "events" },

    // TRANSACTIONS
    "field_transaction_code": {"name": "ID Transação/Pedido (Obrigatório)", "desc": "ID único daquela compra. Essencial para não duplicar vendas.", "category": "transactions" },
    "field_transaction_date": {"name": "Data da Transação (Obrigatório)", "desc": "Data que o pedido foi feito na plataforma (Não usar update).", "category": "transactions" },
    "field_product": {"name": "Nome do Produto (Obrigatório)", "desc": "Nome comercial do seu curso/serviço.", "category": "transactions" },
    "field_product_code": {"name": "ID/SKU do Produto", "desc": "Código identificador do plano interno.", "category": "transactions" },
    "field_quantity": {"name": "Quantidade Comprada", "desc": "Quantidade do mesmo produto que foi para o carrinho.", "category": "transactions" },
    "field_transaction_value": {"name": "Valor Transacionado Bruto", "desc": "Quanto valia a transação cheia (sem tirar taxa).", "category": "transactions" },
    "field_net_value": {"name": "Valor Líquido", "desc": "Lucro ou Valor real que caiu após a remoção de taxas.", "category": "transactions" },
    "field_marketplace_comission": {"name": "Comissão/Taxa da Plataforma", "desc": "Quanto a plataforma cobrou pelo processamento.", "category": "transactions" },
    "field_transaction_status": {"name": "Status da Transação (Obrigatório)", "desc": "Aprovado, Aguardando, Boleto Impresso, Chargeback.", "category": "transactions" },
    "field_cancellation_date": {"name": "Data de Cancelamento/Refund", "desc": "Data que ocorreu o Churn ou solicitação do estorno.", "category": "transactions" },
    "field_offer": {"name": "Variante da Oferta", "desc": "Variação de precificação ou oferta (Descontos nativos).", "category": "transactions" },
    "field_offer_code": {"name": "Código da Oferta", "desc": "Link do Cód. Checkout.", "category": "transactions" },
    "field_source": {"name": "Plataforma/Gateway", "desc": "Onde ela foi feita. Ex: Hotmart, Kiwify, MercadoPago.", "category": "transactions" },
    "field_charge_type": {"name": "Tipo de Cobrança", "desc": "Ex: Cobrança Única Mensalidade Avulsa ou Recorrência Fixa.", "category": "transactions" },
    "conversion": {"name": "Tag / Evento", "desc": "O que registou essa compra via UTM orgânica?", "category": "transactions" },
    "field_payment_method": {"name": "Meio de Pagamento", "desc": "Cartão de Crédito, PIX, Boleto.", "category": "transactions" },
    "field_installments": {"name": "Número de Parcelas", "desc": "Quantas vezes a pessoa usou o cartão (Apenas números).", "category": "transactions" },
    "field_charge_amount": {"name": "Ordem Mensalidade (Recorrência)", "desc": "Para medir Cohort. É a mensalidade 1? Ou já está na renovação 3?", "category": "transactions" },
    "field_transaction_type": {"name": "Tipo de Item Vendido", "desc": "Foi o item principal ou foi um Order Bump / Upsell secundário?", "category": "transactions" },
    "field_coupon": {"name": "Cupom de Desconto", "desc": "Cupom aplicado caso via oferta relâmpago.", "category": "transactions" },
    "field_zip_code": {"name": "CEP / Zip Code", "desc": "CEP para cálculo de calor de frete.", "category": "transactions" },
    "field_state": {"name": "Estado (UF)", "desc": "", "category": "transactions" },
    "field_city": {"name": "Cidade", "desc": "", "category": "transactions" },
    "field_neighborhood": {"name": "Bairro", "desc": "", "category": "transactions" },

    // SURVEY
    "field_income": {"name": "Renda Individual", "desc": "A pessoa declarou qual salário / lucro bruto?", "category": "survey" },
    "field_familiar_income": {"name": "Renda Familiar Agregada", "desc": "Montante familiar.", "category": "survey" },
    "field_wage_range": {"name": "Faixa Salarial IBGE", "desc": "Ex: Classe A, B, C.", "category": "survey" },
    "field_age": {"name": "Idade Ativa", "desc": "Data de nascimento ou idade preenchida.", "category": "survey" },
    "field_gender": {"name": "Gênero Declarado", "desc": "Homem, Mulher, Outros...", "category": "survey" },
    "field_education": {"name": "Escolaridade e Graduação", "desc": "Analfabeto, Nível Superior...", "category": "survey" },
    "field_profession": {"name": "Cargo Atual / Profissão", "desc": "Engenheiro, Médico.", "category": "survey" },
    "field_profession_area": {"name": "Ecossistema/Saga de Indústria", "desc": "Tecnologia, Saúde, Educação.", "category": "survey" },
    "field_region": {"name": "Região Demográfica", "desc": "Norte, Sul, Sudeste.", "category": "survey" },
    "field_time_following": {"name": "Há quanto tempo nos Sabe?", "desc": "Mapeia maturidade antes do cliente entrar.", "category": "survey" },
    "field_nps": {"name": "NPS (Satisfação 0-10)", "desc": "Mede detrator x promotor.", "category": "survey" }
};

export const TRANS_STATUS_MAP: Record<string, string> = {
    'paid': 'approved', 'approved': 'approved', 'paga': 'approved', 'aprovada': 'approved', 
    'completo': 'approved', 'concluída': 'approved', 'concluida': 'approved', 'entregue': 'approved',
    'aprovado': 'approved', 'success': 'approved', 'authorized': 'approved',
    'waiting_payment': 'pending', 'pending': 'pending', 'pendente': 'pending', 
    'aguardando_pagamento': 'pending', 'em_processamento': 'pending', 'waiting': 'pending',
    'aguardando': 'pending', 'boleto_impresso': 'pending', 'billet_printed': 'pending',
    'refused': 'cancelled', 'cancelled': 'cancelled', 'cancelada': 'cancelled', 'failed': 'cancelled', 
    'rejeitada': 'cancelled', 'cancelado': 'cancelled', 'negada': 'cancelled', 'falhou': 'cancelled',
    'estornado_por_fraude': 'cancelled',
    'refunded': 'refunded', 'reembolsada': 'refunded', 'estornada': 'refunded', 'reembolsado': 'refunded',
    'chargeback': 'refunded', 'contestada': 'refunded'
};

export const HARD_MAPPINGS: Record<string, string> = {
    "Código da transação": "field_transaction_code",
    "Nome do(a) Afiliado(a) + Comprador(a)": "field_name",
    "Email do(a) Comprador(a)": "field_email",
    "Telefone": "field_phone",
    "Documento": "field_cpf",
    "Data da transação": "field_transaction_date",
    "Código do produto + Produto + Faturamento líquido do(a) Produtor(a) + Faturamento do(a) Coprodutor(a) + Transação do Produto Principal": "field_product",
    "Produto": "field_product",
    "Código do produto": "field_product_code",
    "Quantidade de itens": "field_quantity",
    "Valor de compra com impostos": "field_transaction_value",
    "Faturamento líquido": "field_net_value",
    "Status da transação": "field_transaction_status",
    "Nome deste preço": "field_offer",
    "Código do preço": "field_offer_code",
    "Tipo de cobrança": "field_charge_type",
    "Código SCK": "utm_term",
    "Método de pagamento": "field_payment_method",
    "Quantidade total de parcelas": "field_installments",
    "Quantidade de cobranças": "field_charge_amount",
    "Código de cupom": "field_coupon",
    "Código postal": "field_zip_code",
    "Estado / Província": "field_state",
    "Cidade": "field_city",
    "Bairro": "field_neighborhood"
};

export const UNIVERSAL_PRESETS: Record<string, string> = {
    "email": "field_email",
    "e-mail": "field_email",
    "e_mail": "field_email",
    "phone": "field_phone",
    "telefone": "field_phone",
    "celular": "field_phone",
    "whatsapp": "field_phone",
    "wpp": "field_phone",
    "name": "field_name",
    "nome": "field_name",
    "utm_source": "utm_source",
    "utm-source": "utm_source",
    "utmsource": "utm_source",
    "source": "utm_source",
    "utm_medium": "utm_medium",
    "utm-medium": "utm_medium",
    "utmmedium": "utm_medium",
    "utm_campaign": "utm_campaign",
    "utm-campaign": "utm_campaign",
    "utmcampaign": "utm_campaign",
    "campaign": "utm_campaign",
    "utm_content": "utm_content",
    "utm-content": "utm_content",
    "utmcontent": "utm_content",
    "utm_term": "utm_term",
    "utm-term": "utm_term",
    "utmterm": "utm_term",
};

export const PLATFORM_PRESETS: Record<string, Record<string, string>> = {
    "Transactions": {
        "codigodatransacao": "field_transaction_code",
        "nomedoafiliadocomprador": "field_name",
        "emaildocomprador": "field_email",
        "telefone": "field_phone",
        "documento": "field_cpf",
        "datatransacao": "field_transaction_date",
        "codigodoprodutoprodutofaturamentoliquidodoprodutorfaturamentodocoprodutortransacaodoprodutoprincipal": "field_product",
        "quantidadedeitens": "field_quantity",
        "valordecompracomimpostos": "field_transaction_value",
        "faturamentoliquido": "field_net_value",
        "statusdatatransacao": "field_transaction_status"
    }
};
